import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Setting",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative h-full px-8 pt-24">
      {children}
    </div>
  );
}
