import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <header className="bg-gray-100 p-4">Chat</header>
        <div className="grid grid-cols-12 flex-1">
          <aside className="bg-gray-800 text-white p-4 col-span-2">
            foo
          </aside>
          <main className="col-span-10">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
